version: '3'

services:
  indexer-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8010:8010"
    depends_on:
      - unoserver
    environment:
      - UNOSERVER_HOST=unoserver
      - UNOSERVER_PORT=2003
      
  unoserver:
    image: ghcr.io/unoconv/unoserver-docker
    ports:
      - "2003:2003"
    restart: unless-stopped