version: '3'

services:
  indexer-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8009:8009"
    depends_on:
      - unoserver
    env_file:
      - .env
    environment:
      - UNOSERVER_HOST=unoserver
      - UNOSERVER_PORT=2003
      - DB_URL=${DB_URL}
      - LOG_LEVEL=${LOG_LEVEL}
      - INFERENCE_API_KEY=${INFERENCE_API_KEY}
      - INFERENCE_API_BASE=${INFERENCE_API_BASE:-http://modelrouter-api:8000/v1}
      - EMBEDDING_API_KEY=${EMBEDDING_API_KEY}
      - EMBEDDING_API_BASE=${EMBEDDING_API_BASE:-http://modelrouter-api:8000/v1}
    volumes:
      - ./:/app
    networks:
      - model-router-network
  unoserver:
    container_name: unoserver
    image: ghcr.io/unoconv/unoserver-docker
    ports:
      - "2003:2003"
    restart: unless-stopped
    networks:
      - model-router-network

volumes: {}

networks:
  model-router-network:
    external: false