version: '3.8'

services:
  agentapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agentapp
    ports:
      - "8000:8000"
      - "5678:5678"  
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app/app
      - PYTHONUNBUFFERED=1
    volumes:
      - ./logs:/app/logs
      - .:/app
    restart: unless-stopped
    # Run app automatically without debugpy
    command: ["sh", "-c", "python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"]
