version: '3.8'

services:
  agentapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agentapp
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app/app
      - PYTHONUNBUFFERED=1
    volumes:
      - ./logs:/app/logs
      - .:/app
    restart: unless-stopped
    command: ["sh", "-c", "python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"]


  agentapp-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: agentapp-dev
    ports:
      - "8000:8000"
      - "5678:5678"
    env_file:
      - .env
    environment:
      - PYTHONPATH=.
      - PYTHONUNBUFFERED=1
    volumes:
      - ./logs:/app/app/logs
      - ./app:/app/app
    working_dir: /app/app
    restart: unless-stopped
    command: ["sh", "-c", "python3 -m debugpy --listen 0.0.0.0:5678 --wait-for-client -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload"]
