version: '3.8'

services:
  agent-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agent-api
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - OPENAI_API_KEY=${OPENAI_API_KEY:-test-key}
      - OPENAI_API_BASE=${OPENAI_API_BASE:-http://192.5.87.119:8000/v1}
      - TAVILY_API_KEY=${TAVILY_API_KEY:-your-tavily-key}
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    volumes:
      - ./logs:/app/logs
      - agent-api-data:/app/data
    restart: unless-stopped
    networks:
      - agent-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
volumes:
  agent-api-data:

networks:
  agent-network:
    driver: bridge
