version: '3.8'

services:
  modelrouter-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL:-https://api.openai.com/v1}
      - HUGGINGFACE_API_TOKEN=${HUGGINGFACE_API_TOKEN:-}
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://ollama:11434}
      - DATABASE_URL=sqlite:///./modelrouter.db
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    volumes:
      - ./:/app
      - model-router-data:/app/data
    restart: unless-stopped
    networks:
      - model-router-network
    depends_on:
      - ollama

  ollama:
    container_name: ollama
    image: ollama/ollama:0.7.0
    volumes:
      - ollama-data:/root/.ollama
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - OLLAMA_NUM_CTX=$(OLLAMA_NUM_CTX:-8096)
      - OLLAMA_KV_CACHE_TYPE=q8_0
      - OLLAMA_FLASH_ATTENTION=1
    restart: unless-stopped
    networks:
      - model-router-network

volumes:
  model-router-data:
  ollama-data:

networks:
  model-router-network:
    name: model-router-network
    driver: bridge
    external: true