version: '3.8'

services:
  modelrouter-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL:-https://api.openai.com/v1}
      - HUGGINGFACE_API_TOKEN=${HUGGINGFACE_API_TOKEN:-}
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://ollama:11434}
      - DATABASE_URL=sqlite:///./modelrouter.db
      - NVIDIA_VISIBLE_DEVICES=all
      - DEEPSEEK_BASE_URL=${DEEPSEEK_BASE_URL:-}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY:-}
      - QWEN_BASE_URL=${QWEN_BASE_URL:-}
      - QWEN_API_KEY=${QWEN_API_KEY:-}
      - OPENAI_ORGS=${OPENAI_ORGS:-}
      - HUGGINGFACE_MODELS=${HUGGINGFACE_MODELS:-}
      - OLLAMA_MODELS=${OLLAMA_MODELS:-}
      - OPENAI_MODELS=${OPENAI_MODELS:-}
      - DEEPSEEK_MODELS=${DEEPSEEK_MODELS:-}
      - QWEN_MODELS=${QWEN_MODELS:-}
      - TEXT_GENERATION_MODELS=${TEXT_GENERATION_MODELS:-}
      - TEXT_EMBEDDING_MODELS=${TEXT_EMBEDDING_MODELS:-}
      - IMAGE_EMBEDDING_MODELS=${IMAGE_EMBEDDING_MODELS:-}
      - RERANKER_MODELS=${RERANKER_MODELS:-}
      - OLLAMA_DEFAULT_NUM_CTX=${OLLAMA_DEFAULT_NUM_CTX:-}
    gpus: all
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - capabilities: [gpu]
    volumes:
      - ./:/app
      - model-router-data:/app/data
    restart: unless-stopped
    networks:
      - model-router-network
    depends_on:
      - ollama

  ollama:
    container_name: ollama
    image: ollama/ollama:0.7.0
    volumes:
      - ollama-data:/root/.ollama
    gpus: all
    ports:
      - "11434:11434"
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - OLLAMA_NUM_CTX=$(OLLAMA_NUM_CTX:-8096)
      # - OLLAMA_KV_CACHE_TYPE=$(OLLAMA_KV_CACHE_TYPE:-q8_0)
      # - OLLAMA_FLASH_ATTENTION=$(OLLAMA_FLASH_ATTENTION:-1)
    restart: unless-stopped
    networks:
      - model-router-network

volumes:
  model-router-data:
  ollama-data:

networks:
  model-router-network:
    name: model-router-network
    driver: bridge
    external: true