version: '3.8'

services:
  modelrouter-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL:-https://api.openai.com/v1}
      - HUGGINGFACE_API_TOKEN=${HUGGINGFACE_API_TOKEN:-}
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://ollama:11434}
      - DATABASE_URL=sqlite:///./modelrouter.db
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    volumes:
      - ./:/app
      - model-router-data:/app/data
    restart: unless-stopped
    networks:
      - model-router-network
    depends_on:
      - ollama

  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    volumes:
      - ollama-data:/root/.ollama
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - MODEL_NAME=${MODEL_NAME:-gemma3:12b-it-q8_0}
      - CTX_SIZE=${CTX_SIZE:-80000}
    entrypoint:
      - sh
      - -c
      - |
        exec ollama serve "$MODEL_NAME" \
          --ctx-size "$CTX_SIZE" \
          --batch-size 1 \
          --n-gpu-layers 10 \
          --threads 40 \
          --parallel 1
    restart: unless-stopped
    networks:
      - model-router-network

volumes:
  model-router-data:
  ollama-data:

networks:
  model-router-network:
    name: model-router-network
    driver: bridge
    external: true